stages:
    - deploy
    - change

deploy-dev:
  stage: deploy
  only:
    - develop
  script:
    - cd /var/www/frontend
    - git reset --hard
    - git clean -f
    - git pull origin develop
    - cp .env.develop .env
    - npm install
    - npm run build
  tags:
    - dev-front

change-dev:
  stage: change
  only:
    - develop
  script:
    - chown -R webapp. /var/www/*
  tags:
    - dev-front

